mcc -m ChaCoCalc.m -I /Users/Jimmy/Documents/nemo/LoCoTool/Files/Atlasing ...
-I /Users/Jimmy/Documents/nemo/LoCoTool/Files/spm8 ...
-I /Users/Jimmy/Documents/nemo/LoCoTool/Files/nifti_toolbox ...
-I /Users/Jimmy/Documents/nemo/LoCoTool/Files/ODF_Qball ...
-I /Users/Jimmy/Documents/nemo/LoCoTool/Files/Tracking_Bayes ...
-I /Users/Jimmy/Documents/nemo/LoCoTool/Files/mymfiles ...
-I /Users/Jimmy/Documents/nemo/LoCoTool/Files/trunk/eve_tools ...
-I /Users/Jimmy/Documents/nemo/LoCoTool/Files/trunk/LoCoTool ...
% mcc -m ChaCoCalc.m -I Z:/Documents/nemo/LoCoTool/Files/Atlasing ...
% -I Z://Documents/nemo/LoCoTool/Files/spm8 ...
% -I Z://Documents/nemo/LoCoTool/Files/nifti_toolbox ...
% -I Z://Documents/nemo/LoCoTool/Files/ODF_Qball ...
% -I Z://Documents/nemo/LoCoTool/Files/Tracking_Bayes ...
% -I Z://Documents/nemo/LoCoTool/Files/mymfiles ...
% -I Z://Documents/nemo/LoCoTool/Files/trunk/eve_tools ...
% -I Z://Documents/nemo/LoCoTool/Files/trunk/LoCoTool ...